name: Deploy to Test Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: composite-actions
          ref: main


      - name: node-operation
        uses: ./composite-actions/.github/actions/node-operation
        working-directory: ./src
        with:
          node-version: "18"
          node-command: "yarn install --no-progress --frozen-lock && yarn build && rm -rf node_modules"


